with st as (select * from {{ source('silver','sl_staff') }}),
     s  as (select * from {{ source('silver','sl_store') }}),
     a  as (select * from {{ source('silver','sl_address') }})
select
  md5(cast(st.staff_id as text))::uuid as gl_dim_staff_key,
  st.staff_id,
  st.first_name,
  st.last_name,
  st.full_name,
  st.email,
  st.username,
  st.is_active,
  st.store_id,
  a.address as store_address,
  null::varchar(50) as store_city,
  (st.store_id = s.store_id and st.staff_id = s.manager_staff_id) as is_store_manager,
  null::varchar(50) as address_line1,
  null::varchar(50) as address_line2,
  null::varchar(20) as district,
  null::varchar(50) as city,
  null::varchar(10) as postal_code,
  null::varchar(20) as phone,
  null::varchar(50) as country,
  coalesce(st.last_update, now()) as last_update,
  0 as total_rentals_processed,
  0 as total_payments_processed,
  0.00::numeric(12,2) as total_payment_amount,
  null::numeric(6,2) as avg_payment_amount,
  null::float as avg_rentals_per_day,
  null::float as avg_payments_per_day,
  null::float as customer_satisfaction_score,
  null::varchar(20) as performance_tier,
  false as is_top_performer,
  null::varchar(25) as specialization,
  null::int as managed_staff_count,
  null::numeric(12,2) as store_revenue_under_management,
  null::float as team_performance_score
from st
left join s on s.store_id = st.store_id
left join a on a.address_id = s.address_id
